### ISSUE TITLE
相对链接问题

### ISSUE THREAD

**Issue by viko16** [jackhutu/jackblog-vue#1]
## 问题

直接访问 demo 中[随便一篇文章](http://vue.jackhu.top/article/560a438f10f611091d0933c6)，看看是否显示正常。

会发现访问了 
`http://vue.jackhu.top/article/xxx.js` 
而不是正确的
 `http://vue.jackhu.top/xxx.js`
## 猜测
- `vue-router` 开启了 HTML5 history 模式后，会出现 `http://vue.jackhu.top/article/:aid` 的形式的 URL
- `html-webpack-plugin` 输出的 HTML 只包含了简单相对路径的静态资源引用
## 建议

参考[官方文档](http://webpack.github.io/docs/configuration.html#output-publicpath)，`webpack` 打包时加上 `publicPath`，把链接变成绝对链接可以避免这个问题。

**Comment by hutuxuhui** [comment]
谢谢提醒, 确实要加上 publicPath.
