### ISSUE TITLE
3001admin 登录问题

### ISSUE THREAD

**Issue by nonacosa** [jackhutu/jackblog-vue#10]
我登录之后通过    auto验证之后admin还是未登录状态  3000博客也没登录
登录到你的.top域名下了，请问如何修改，才能在我的本地搭建前后分离的博客系统，我可以本地管理呢？

**Comment by hutuxuhui** [comment]
开发环境应该是没问题的,生产环境改一下配置, 去掉cookie的domain限制.

**Comment by nonacosa** [comment]
好的，感谢 @jackhutu
