### ISSUE TITLE
great work

### ISSUE THREAD

**Issue by haisapan** [jackhutu/jackblog-vue#11]
This is not an **issue**, but a **message** for you:
**
1.  Can you share something about these framework when developing your blog? like framework comparison, and which one is better for this project?
2. It should be better if we have a forum or gitter to discuss it.

**

BTW, wonderful job.
 thanks

**Comment by hutuxuhui** [comment]
Thank you. I will try to improve the angular2 and vue2 version, there may be some share. If you want to discuss can leave a message in my blog.
