### ISSUE TITLE
启动的时候出现 error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

### ISSUE THREAD

**Issue by mawenge** [jackhutu/jackblog-vue#13]
开发环境是windows，请问是不是哪里需要配置

**Comment by hutuxuhui** [comment]
配置了eslint代码检查, linebreak-style 这一行估计在windows要改一下.

**Comment by mawenge** [comment]
解决了，在.eslintrc.json文件中把rules下面的"linebreak-style": [
  "error",
  "windows"
],
修改成
"linebreak-style":0,
就可以了
gulp配置也不太懂，现在看这个项目暂时略过gulp应该没什么影响吧

**Comment by hutuxuhui** [comment]
完全没影响, 只是用来启动webpack而已

**Comment by Lover103** [comment]
Adding a .editorconfig plugin for your IDE/editor solves it?

This file configures the editor to add an LF on line endings: https://github.com/diegohaz/arc/blob/master/.editorconfig

**Comment by kvsur** [comment]
> 解决了，在.eslintrc.json文件中把rules下面的"linebreak-style": [
"error",
"windows"
],
修改成
"linebreak-style":0,
就可以了
gulp配置也不太懂，现在看这个项目暂时略过gulp应该没什么影响吧

@mawenge 有些版本或者在rules中没有linebreak-style这个配置项，有时候需要自己加上就可以了

**Comment by yudetchu** [comment]
感恩

**Comment by adouwt** [comment]
![image](https://user-images.githubusercontent.com/22048974/56113043-4ab74e80-5f8f-11e9-9051-ddff41f10e1d.png)
