### ISSUE TITLE
启动报关于图片模块导入的错误，希望可以指导下哈

### ISSUE THREAD

**Issue by piaopiaoran** [jackhutu/jackblog-vue#14]
ERROR in ./~/.6.4.1@babel-loader/lib!./~/.1.7.1@eslint-loader!./~/.8.7.0@vue-loader/lib/selector.js?type=script&index=0!./src/components/Navbar.vue
Module not found: Error: Cannot resolve module 'image-webpack' in /Users/jinyunyan/Desktop/test/vuetest/jackblog-vue/src/components
 @ ./~/.6.4.1@babel-loader/lib!./~/.1.7.1@eslint-loader!./~/.8.7.0@vue-loader/lib/selector.js?type=script&index=0!./src/components/Navbar.vue 9:14-52

ERROR in ./~/.6.4.1@babel-loader/lib!./~/.1.7.1@eslint-loader!./~/.8.7.0@vue-loader/lib/selector.js?type=script&index=0!./src/components/Article/comment.vue
Module not found: Error: Cannot resolve module 'image-webpack' in /Users/jinyunyan/Desktop/test/vuetest/jackblog-vue/src/components/Article

**Comment by hutuxuhui** [comment]
可能需要安装libpng这东东.
