### ISSUE TITLE
请教一个项目构建问题

### ISSUE THREAD

**Issue by mawenge** [jackhutu/jackblog-vue#15]
博主，你好，下载了你的express版server代码跟vue版的代码，我对node的运行原理基本了解，也基本能看懂你的express的server代码，但是看到你的vue版的项目的时候有一些疑惑，首先express版的项目是作为一个服务器版本在跑，我理解vue版的项目应该也是通过请求node服务器数据进行页面显示的，那么vue版的项目应该也是一个独立的server服务器，通过node构建服务器项目我是比较理解的，node是运行在v8引擎上的；但是通过vue构建服务器项目我有一些不太懂，这个又是什么原理呢？
如果有现成的介绍贴个链接也可以，不甚感激！！！

**Comment by hutuxuhui** [comment]
vue项目是前端项目,跑在浏览器的. 只是部署的时候, 用node起个web服务, 方便http访问而已.
