### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by piaopiaoran** [jackhutu/jackblog-vue#16]
Dear author:
本人水平一般，希望可以知道下哈，
![image](https://cloud.githubusercontent.com/assets/15925788/26403031/38f70154-40bf-11e7-8910-d3c88b8d7f63.png)

对于你的getters为什么这样写，或者类似这些，变量是从哪里来的，我真的是看不懂哈，

**Comment by hutuxuhui** [comment]
你可能要仔细看看vuex文档.... 整个状态树是从根元素传进来的.
