### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by cobola** [jackhutu/jackblog-vue#18]
ERROR in ./src/index.js
Module build failed: TypeError: Cannot read property 'base' of undefined
Referenced from: /...../jackblog-vue/.eslintrc.json

什么情况呢？代码更新的最新的

**Comment by cobola** [comment]
"extends": [
    "eslint:recommended"
    //"plugin:vue/base"

把这个注释掉就好了

**Comment by hutuxuhui** [comment]
应该装了eslint-plugin-vue不会有这个报错, 是node几呀.

**Comment by hutuxuhui** [comment]
重新调整了eslint配置, 现在改成plugin:vue/recommended了.
