### ISSUE TITLE
用户注册

### ISSUE THREAD

**Issue by mlyknown** [jackhutu/jackblog-vue#2]
看了demo,没有注册的地方啊？

**Comment by hutuxuhui** [comment]
是的, 没有做注册的功能, 只有第三方登录. 应该没人到小博客网站注册, 账号登录是给管理员登录的.  :))

**Comment by mlyknown** [comment]
那现在需要自己在mongodb里面加一条数据了?

**Comment by mlyknown** [comment]
而且怎么写博客啊。。。没找到 0.0

**Comment by hutuxuhui** [comment]
后台管理用的这个[https://github.com/jackhutu/jackblog-admin](https://github.com/jackhutu/jackblog-admin)
