### ISSUE TITLE
建立一个QQ群针对该博客的技术进行讨论

### ISSUE THREAD

**Issue by cute1baby** [jackhutu/jackblog-vue#20]
希望能建立一个群来对这个技术进行讨论，我希望能作为发起人。我的QQ是:1138724604.如果您有意愿的话希望能帮助你建立一个博客技术社群。

**Comment by hutuxuhui** [comment]
之前好像有人建过一个qq群.

**Comment by gozelus** [comment]
前端小白，仔细看了下项目，发现.vue文件中都没有css的部分，请问这是怎么做的呢？

**Comment by hutuxuhui** [comment]
没错, 我这里只是为了让多个版本共享一套css, 所以将css文件放在一个npm包里了.
