### ISSUE TITLE
error

### ISSUE THREAD

**Issue by moqinai** [jackhutu/jackblog-vue#21]
ERROR in ./src/assets/images/shanghai.jpg
Module build failed: Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/lipengcheng/Documents/gitBendi/jackblog-vue/node_modules/mozjpeg/vendor/cjpeg
  Reason: image not found

    at Promise.all.then.arr (/Users/lipengcheng/Documents/gitBendi/jackblog-vue/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/store/actions.js 16:16-56
 @ ./src/store/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/index

**Comment by hutuxuhui** [comment]
装了libpng这个没
