### ISSUE TITLE
修改运行方式为npm run dev。

### ISSUE THREAD

**Issue by rts-gordon** [jackhutu/jackblog-vue#3]
Hi jackhutu: 从网上搜索到jackblog项目，正在学习。请问可不可以把jackblog的运行方式修改为nmp run dev/build，因为现在项目用gulp的少了。依赖的工具越少越好。谢谢。

**Comment by hutuxuhui** [comment]
当然可以, gulp在本项目中只是调用了webpack, 如果不使用gulp可以参考jackblog-react-redux这个. 但是即便不用gulp,也会使用其它库,来顺序执行任务. 这都小事.
