### ISSUE TITLE
增加用户注册功能。

### ISSUE THREAD

**Issue by rts-gordon** [jackhutu/jackblog-vue#4]
目前只有用户登录功能，或者使用其他系统用户登录，是否可以增加用户注册功能，这对于一个完整的系统来说是必要的。可以使用邮箱验证用户。谢谢。

**Comment by hutuxuhui** [comment]
这个功能很简单, 但是在博客注册的人估计不多, 如果是想自己建博客, 可以自己添加这个功能.
