### ISSUE TITLE
请问，在api封装中 controller是什么意思 我没看明白

### ISSUE THREAD

**Issue by zhuewizz** [jackhutu/jackblog-vue#8]

**Comment by hutuxuhui** [comment]
相當於promise封裝,同時簡化API請求結構.

**Comment by zhuewizz** [comment]
谢谢
   我在消化一下！

|
|

zhuweizz@126.com
深圳市美思美科智能科技股份有限公司
深圳市龙华观澜环观中路易顺达电子商务物流园
电话：23031426
手机：13502865241
|

扫描该二维码，可以将电子名片迅速保存到手机 使用帮助

|
|

在 2016-07-19 01:38:27，"Jack Hu" notifications@github.com 写道：

相當於promise封裝,同時簡化API請求結構.
